### ISSUE TITLE
"Omeka S encountered an error" while attempting to install.

### ISSUE THREAD

**Issue by akprtll** [Daniel-KM/Omeka-S-module-Correction#2]
I'm receiving an error message that begins "Doctrine\DBAL\Exception\TableExistsException" when I try to install Correction (after installing the Generic module, which seems to install with no problems).

Here is the full error message I'm receiving: https://pastebin.com/0z4LKWVv

**Comment by Daniel-KM** [comment]
There was a previous install that is not uninstalled fully for an unknown reason. You have to remove the existing tables directly in the database.

**Comment by akprtll** [comment]
I was able to delete the tables and then reinstalled the Generic and Correction modules, but was still unable to get it to work. I tried creating a fresh installation of Omeka S and loading Generic and then Correction but received an error in that case as well. Perhaps I will revisit trying out this plugin again in a few weeks down the road. Thanks for the guidance!

**Comment by Daniel-KM** [comment]
Yes, comments will be converted in real annotations in some time.
